//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""564e623f-c2e0-44a7-8cde-5fdd8b042597"",
            ""actions"": [
                {
                    ""name"": ""Pan_X"",
                    ""type"": ""Button"",
                    ""id"": ""0d22165f-f9de-4bd3-b1f4-8b55e39d111b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pan_Y"",
                    ""type"": ""Button"",
                    ""id"": ""50416d96-0a4e-42ab-aedd-e6d1e8bf861c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pan_Z"",
                    ""type"": ""Button"",
                    ""id"": ""927a67f3-81b8-4a24-b45a-adf2fa6122f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""69dd911e-fa29-4fa5-8047-17be11515c3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraSelection"",
                    ""type"": ""Button"",
                    ""id"": ""cbce4355-d4cf-47f7-af25-a005dc916b19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause/Play"",
                    ""type"": ""Button"",
                    ""id"": ""32827d5b-a59c-4caa-b4d0-dfe26e62e9ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeRoam"",
                    ""type"": ""Button"",
                    ""id"": ""d7246d11-8d8f-49d5-861f-439678101bf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""Button"",
                    ""id"": ""3ed28a0b-cac5-4750-b76e-f21861962009"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Missile_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""a75d986b-ad6d-4f98-a70e-362de59976d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""49b8f7ea-3402-426f-b7a7-c18265ea967f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_X"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""376cdfe6-56d0-4c81-8abb-831595d04221"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a09321e3-c482-4f2a-886f-d30287acf818"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""17a2c2a8-9498-41ec-b64d-9beb6702a995"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Y"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7539ff63-a368-44ff-b262-c8b81af055bc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""698bb4b6-b8ef-41cb-922c-94ac88ff63e5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""db00a2ab-cf45-4022-a6e6-723ea527c7f1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Z"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""73e074a2-2b02-4311-bb3d-0b8a9ffcbef9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Z"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b4526430-ceda-4e55-8a5b-408f1ab0b642"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan_Z"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""37861eac-03d6-4b63-b104-acc1280d727f"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf015ec0-5d20-42a3-b89b-aec20dc969f2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd2dd85d-afcd-48a8-904e-dfcc2f94535b"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause/Play"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5506cf3-91fe-4649-9119-ac19f263a760"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeRoam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c55e6204-783a-4109-b164-34f105c33635"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a969197-0c57-40f3-a672-b634915c76d3"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Missile_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Pan_X = m_Camera.FindAction("Pan_X", throwIfNotFound: true);
        m_Camera_Pan_Y = m_Camera.FindAction("Pan_Y", throwIfNotFound: true);
        m_Camera_Pan_Z = m_Camera.FindAction("Pan_Z", throwIfNotFound: true);
        m_Camera_Rotation = m_Camera.FindAction("Rotation", throwIfNotFound: true);
        m_Camera_CameraSelection = m_Camera.FindAction("CameraSelection", throwIfNotFound: true);
        m_Camera_PausePlay = m_Camera.FindAction("Pause/Play", throwIfNotFound: true);
        m_Camera_FreeRoam = m_Camera.FindAction("FreeRoam", throwIfNotFound: true);
        m_Camera_Position = m_Camera.FindAction("Position", throwIfNotFound: true);
        m_Camera_Missile_Trigger = m_Camera.FindAction("Missile_Trigger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera
    private readonly InputActionMap m_Camera;
    private ICameraActions m_CameraActionsCallbackInterface;
    private readonly InputAction m_Camera_Pan_X;
    private readonly InputAction m_Camera_Pan_Y;
    private readonly InputAction m_Camera_Pan_Z;
    private readonly InputAction m_Camera_Rotation;
    private readonly InputAction m_Camera_CameraSelection;
    private readonly InputAction m_Camera_PausePlay;
    private readonly InputAction m_Camera_FreeRoam;
    private readonly InputAction m_Camera_Position;
    private readonly InputAction m_Camera_Missile_Trigger;
    public struct CameraActions
    {
        private @Inputs m_Wrapper;
        public CameraActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pan_X => m_Wrapper.m_Camera_Pan_X;
        public InputAction @Pan_Y => m_Wrapper.m_Camera_Pan_Y;
        public InputAction @Pan_Z => m_Wrapper.m_Camera_Pan_Z;
        public InputAction @Rotation => m_Wrapper.m_Camera_Rotation;
        public InputAction @CameraSelection => m_Wrapper.m_Camera_CameraSelection;
        public InputAction @PausePlay => m_Wrapper.m_Camera_PausePlay;
        public InputAction @FreeRoam => m_Wrapper.m_Camera_FreeRoam;
        public InputAction @Position => m_Wrapper.m_Camera_Position;
        public InputAction @Missile_Trigger => m_Wrapper.m_Camera_Missile_Trigger;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void SetCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterface != null)
            {
                @Pan_X.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_X;
                @Pan_X.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_X;
                @Pan_X.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_X;
                @Pan_Y.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_Y;
                @Pan_Y.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_Y;
                @Pan_Y.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_Y;
                @Pan_Z.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_Z;
                @Pan_Z.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_Z;
                @Pan_Z.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPan_Z;
                @Rotation.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnRotation;
                @CameraSelection.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraSelection;
                @CameraSelection.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraSelection;
                @CameraSelection.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraSelection;
                @PausePlay.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPausePlay;
                @PausePlay.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPausePlay;
                @PausePlay.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPausePlay;
                @FreeRoam.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnFreeRoam;
                @FreeRoam.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnFreeRoam;
                @FreeRoam.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnFreeRoam;
                @Position.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPosition;
                @Missile_Trigger.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMissile_Trigger;
                @Missile_Trigger.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMissile_Trigger;
                @Missile_Trigger.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMissile_Trigger;
            }
            m_Wrapper.m_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pan_X.started += instance.OnPan_X;
                @Pan_X.performed += instance.OnPan_X;
                @Pan_X.canceled += instance.OnPan_X;
                @Pan_Y.started += instance.OnPan_Y;
                @Pan_Y.performed += instance.OnPan_Y;
                @Pan_Y.canceled += instance.OnPan_Y;
                @Pan_Z.started += instance.OnPan_Z;
                @Pan_Z.performed += instance.OnPan_Z;
                @Pan_Z.canceled += instance.OnPan_Z;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @CameraSelection.started += instance.OnCameraSelection;
                @CameraSelection.performed += instance.OnCameraSelection;
                @CameraSelection.canceled += instance.OnCameraSelection;
                @PausePlay.started += instance.OnPausePlay;
                @PausePlay.performed += instance.OnPausePlay;
                @PausePlay.canceled += instance.OnPausePlay;
                @FreeRoam.started += instance.OnFreeRoam;
                @FreeRoam.performed += instance.OnFreeRoam;
                @FreeRoam.canceled += instance.OnFreeRoam;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Missile_Trigger.started += instance.OnMissile_Trigger;
                @Missile_Trigger.performed += instance.OnMissile_Trigger;
                @Missile_Trigger.canceled += instance.OnMissile_Trigger;
            }
        }
    }
    public CameraActions @Camera => new CameraActions(this);
    public interface ICameraActions
    {
        void OnPan_X(InputAction.CallbackContext context);
        void OnPan_Y(InputAction.CallbackContext context);
        void OnPan_Z(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnCameraSelection(InputAction.CallbackContext context);
        void OnPausePlay(InputAction.CallbackContext context);
        void OnFreeRoam(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
        void OnMissile_Trigger(InputAction.CallbackContext context);
    }
}
